public enum MTGAdSourceType
{
	MTGAD_SOURCE_API_OFFER = 1,
	MTGAD_SOURCE_MY_OFFER = 2,
	MTGAD_SOURCE_FACEBOOK = 3,
	MTGAD_SOURCE_MINTEGRAL = 4,
	MTGAD_SOURCE_PUBNATIVE = 5,
	MTGAD_SOURCE_ADMOB = 6,
	MTGAD_SOURCE_MYTARGET = 7,
	MTGAD_SOURCE_NATIVEX = 8,
	MTGAD_SOURCE_APPLOVIN = 9
}
